//stdlib
#include <iostream> //standard i/O header
#include <cerrno> //global variable the kernel use to store the last error
#include <cstdlib>
#include <cstring>
#include <string_view>

//system
#include <sys/socket.h> 
#include <netinet/in.h>
#include <unistd.h> //used to handle file descriptors (read , write , close)
#include <cassert>
#include <poll.h>

//STL
#include <vector>



static void msg(const char *msg) {
    std::cerr << msg << std::endl;
}

static void die(const char *msg) {
    int err = errno;
    std::cerr << "[" << err << "] " << msg << std::endl; /*File Print Format: Unlike standard printf (which always prints to the screen), fprintf allows you to specify exactly where the text should be sent (to a file, a stream, or the screen).*/
    abort();
}


//Data structure to store the state information of each connection to use in the future
struct Conn {
    int fd = -1; //reference to the clients connnection file descriptor

    //to Store the application's intention for this event loop
    bool wantRead = false;
    bool wantWrite = false;
    bool wantClose = false;

    //buffered input and output
    std::vector<uint32_t> incoming; // data to be parsed by the application
    std::vector<uint32_t> outgoing; // responses generated by the application

};



int main() {

            //socket(domain , conn-type , protocol)
    int fd = socket(AF_INET , SOCK_STREAM , 0);
     if (fd < 0) {
        die("socket()");
    }
    
    /*
        1.AF_INET is for IPv4. Use AF_INET6 for IPv6 or dual-stack sockets.
        2.SOCK_STREAM is for TCP. Use SOCK_DGRAM for UDP.
        3.The 3rd argument is 0 and useless for our purposes.
     */
    int val = 1;
    //int setsockopt(int sockfd, int level, int optname,const void optval[.optlen], socklen_t optlen);
    setsockopt(fd ,SOL_SOCKET, SO_REUSEADDR , &val, sizeof(val));

    //bind
    struct sockaddr_in addr = {}; //initiazlise a sockadder_in sturcture
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234); //htons converts the little endian representation to big endian 
    addr.sin_addr.s_addr = htonl(0); // wildcard IP 0.0.0.0
    
    int rv = bind(fd , (const struct sockaddr *)&addr , sizeof(addr));

    if(rv) {
        die("bind()");
    }

    //listen
    rv = listen(fd , SOMAXCONN);
    if(rv) {
        die("listen()");
    }

    std::cout << "Server is listening on port 1234..." << std::endl;

    //start the event loop

     // a map of all client connections, keyed by fd
     std::vector<Conn *> fd2conn; //On Unix, an fd is allocated as the smallest available non-negative integer, so the mapping from fd to Conn can be a flat array indexed by fd

     //the event loop
     std::vector<struct pollfd> poll_args;

     while(true) {

        poll_args.clear(); //It flushes old kernel answers and dead connections so you can build a completely fresh, accurate checklist for the next loop pass.

        // Register the listening socket (server socket bind) to watch for brand-new client connections
        struct pollfd pfd = {fd , POLLIN , 0}; //basically it tells the poll function to wake it when a new connection request comes

        poll_args.push_back(pfd);

        //insert all the existing connection to the poll list
        for(Conn *conn: fd2conn) {
            
            if(!conn) {
                continue;
            }

            struct pollfd pfd = {conn->fd , POLLERR , 0}; //POLLERR ->  Monitor the client socket for connection errors (broken pipes, crashes) by default 

            if(conn->wantWrite) {
                pfd.events = pfd.events | POLLOUT; //bitmasking techinque 
            }
            if(conn->wantRead) {
                pfd.events = pfd.events | POLLIN;
            }
            poll_args.push_back(pfd);
        }

        // wait for readiness (from the inserted connections)
        //nfds_t = unsigned int or long
        int rv = poll(poll_args.data() , (nfds_t)poll_args.size() , -1); // Tell the kernel to watch our sockets;  block indefinitely until an event occurs
        if(rv < 0 && errno == EINTR) {
            continue; //not an error
        }

        if(rv < 0) {
            die("POLL");
        }

        //Accept new connection requests (from the socket at zero index);
        if(poll_args[0].revents) { //revents is filled by the kernel when the client have something to say 

            //
        }
        


     }

   

    return 0;

}