//stdlib
#include <iostream> //standard i/O header
#include <cerrno> //global variable the kernel use to store the last error
#include <cstdlib>
#include <cstring>
#include <string_view>

//system
#include <sys/socket.h> 
#include <netinet/in.h>
#include <unistd.h> //used to handle file descriptors (read , write , close)
#include <cassert>
#include <poll.h>
#include <fcntl.h>

//STL
#include <vector>


//hashmap
#include "hashtable/hashtable.h"

#define container_of(ptr , T , member) \
    ((T *)((char *)ptr - offsetof(T , member)))

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer


static void msg(const char *msg) {
    std::cerr << msg << std::endl;
}

static void msg_errno(const char *msg) {
   std::cerr << "[Error No: " << errno << "] : " << msg << std::endl;
}

static void die(const char *msg) {
    int err = errno;
    std::cerr << "[" << err << "] " << msg << std::endl; /*File Print Format: Unlike standard printf (which always prints to the screen), fprintf allows you to specify exactly where the text should be sent (to a file, a stream, or the screen).*/
    abort();
}

typedef std::vector<uint8_t> Buffer;



//Data structure to store the state information of each connection to use in the future
struct Conn {
    int fd = -1; //reference to the clients connnection file descriptor

    //to Store the application's intention for this event loop
    bool wantRead = false; //Hey loop, I'm waiting for a new command. Please ask poll() to watch for POLLIN
    bool wantWrite = false; //Hey loop, I have unsent bytes trapped in my outgoing buffer. Please ask poll() to watch for POLLOUT
    bool wantClose = false; //Hey loop, I encountered a protocol violation or received an EOF. Please run the delete routine on me during the next cleanup sweep.

    //buffered input and output
    Buffer incoming; // data to be parsed by the application
    Buffer outgoing; // responses generated by the application
    //uint8_t = unsigned int of 8bits = 1bytes (0 - 255)range best for storing streamed data (char , image file , video);

};



static void bufAppend(Buffer &buf , const uint8_t *data , size_t size){
    buf.insert(buf.end() , data , data+size); 
    /**
     *  buf.end() -> pointer to the position after the last available data in the vector
     *  data is the starting address of your raw data.

        data + size uses pointer arithmetic to calculate the ending boundary. In C++, range boundaries are always exclusive (meaning it copies everything up to, but not including, the exact address of data + size).
     */
}

static void bufConsume(Buffer &buf , size_t n){
    buf.erase(buf.begin() , buf.begin()+n);
}

const size_t k_max_args = 200 * 1000;

static bool readU32(const uint8_t*&curr , const uint8_t *end , uint32_t &out) {

    if(curr + 4 > end) {
        return false; //not enough data is recived get more data to parse
    }

    memcpy(&out , curr , 4);
    curr += 4; //move pointr forward to parse new data;
    return true;
}

static bool readStr(const uint8_t *&curr , const uint8_t *end , size_t len , std::string &out) {

    if(curr + len > end) { //not enough data is available
        return false;
    }

    out.assign(curr , curr+len);
    curr += len;
    return true;
}

//data format
//nstr-> number of packets
//len->size of each string
// +------+-----+------+-----+------+-----+-----+------+
// | nstr | len | str1 | len | str2 | ... | len | strn |
// +------+-----+------+-----+------+-----+-----+------+
static int32_t parseRequest(const uint8_t *data , size_t size , std::vector<std::string> &out) {
    const uint8_t *end = data + size;
    uint32_t nstr = 0;
    if(!readU32(data , end , nstr)) { //get the number of messages
        return -1;
    }

    if(nstr > k_max_args) {
        return -1; // Limit exceed
    }

    //now decode every message packet
    while(out.size() < nstr) {

        //1.find the len of each message
        uint32_t len = 0;
        if(!readU32(data , end , len)) {
            return -1;
        }
        //2.parse the message of that length
        out.push_back(std::string()); //insert an empty string to the back 
        if(!readStr(data , end , len ,  out.back())) {
            return -1;
        }
    }

    if(data != end) {
        return -1; //data contains garbage data
    }
    return 0;
}


// error code for TAG_ERR
enum {
    ERR_UNKNOWN = 1,    // unknown command
    ERR_TOO_BIG = 2,    // response too big
};

// data types of serialized data
enum {
    TAG_NIL = 0,    // nil
    TAG_ERR = 1,    // error code + msg
    TAG_STR = 2,    // string
    TAG_INT = 3,    // int64
    TAG_DBL = 4,    // double
    TAG_ARR = 5,    // array
};

//Helper function to help serialization


//Helper functions to generate the response
static void bufAppendU8(Buffer &buf , uint8_t data) {
    buf.push_back(data);
}

static void bufAppendU32(Buffer &buf , uint32_t data) {
    bufAppend(buf , (const uint8_t *)data , 4); //insert the length in 4bytes
}

static void bufAppendI64(Buffer &buf , int64_t data) {
    bufAppend(buf , (const uint8_t *)&data , 8);
}

static void bufAppendDbl(Buffer &buf , double data){
    bufAppend(buf , (const uint8_t *)&data , 8);
}

/**Generate the nil response */
static void outNil(Buffer &out) {
    bufAppendU8(out , TAG_NIL);
}

static void outStr(Buffer &out , const char *s , size_t size) {
    bufAppendU8(out , TAG_STR); //insert the tag as string (1 byte)
    bufAppendU32(out , (uint32_t)size);  //push the size of the message (4bytes)
    bufAppend(out , (const uint8_t *)s , size);

}

//generate the int response
static void outInt(Buffer &out , uint64_t val) {
    bufAppendU8(out , TAG_INT);
    bufAppendI64(out , val);
}

static void outArr(Buffer &out , uint32_t n) {
    bufAppendU8(out , TAG_ARR); //Tag as array
    bufAppendU32(out , n); //len of the array
}

static void outDbl(Buffer &out , double val) {
    bufAppendU8(out , TAG_DBL);
    bufAppendDbl(out , val);
}

static void outErr(Buffer &out , uint32_t code , const std::string &msg) {
    bufAppendU8(out , TAG_ERR); //tag err
    bufAppendU32(out , code); //error code
    bufAppendU32(out , (uint32_t)msg.size()); //msg length
    bufAppend(out , (const uint8_t*)msg.data() , msg.size());
}


// global states hashmap
static struct {
    HMap db; //top-level hashtable
} gData;

// KV pair for the top-level hashtable
struct Entry {
    struct HNode node; //hashtable node
    std::string key;
    std::string val;
};

//function to check the match for the keys
static bool entryEq(HNode *lhs , HNode *rhs) {
    struct Entry *le = container_of(lhs , struct Entry , node);
    struct Entry *re = container_of(rhs , struct Entry , node);
    return le->key == re->key;
}

//FNV hash function
static uint64_t strHash(const uint8_t *data, size_t len) {
    // 1. Initialize the accumulator with the FNV Offset Basis (Magic Number).
    // This seeds the hash with a chaotic bit pattern so that empty strings 
    // or strings starting with 0x00 do not accidentally result in a hash of zero.
    uint32_t h = 0x811C9DC5;

    // 2. Loop through every character/byte in the input string sequentially.
    for (size_t i = 0; i < len; i++) {
        // Step A: Stir the current byte directly into our hash accumulator.
        // Step B: Multiply by the FNV Prime (0x01000193, which is 16,777,619 in decimal).
        // 
        // This multiplication acts as a high-speed bit mixer, forcing every new 
        // byte to ripple and cascade across all 32 bits (the "avalanche effect").
        // Any integer overflow here is safe, wrapping around naturally via modulo 2^32.
        h = (h + data[i]) * 0x01000193;
    }

    // 3. Return the fully scrambled 32-bit integer hash value.
    // The compiler automatically zero-extends this 32-bit value into a 64-bit 
    // uint64_t, leaving the upper 32 bits as zeros, matching our HNode definition.
    return h;
}



/**
 * 
 * REDIS FUNCTIONS (GET , SET , DEL)
 */

static void doGet(std::vector<std::string> &cmd , Buffer &out) {

    // cmd = {method , key , value}
    Entry dummy; //create a dummy node just for lookup 
    dummy.key.swap(cmd[1]); //insert the value of key

    dummy.node.hcode = strHash((uint8_t *)dummy.key.data() , dummy.key.size()); //generate the hash for the key we are looking

    //hashtable lookup
    HNode *nodeFound = hmLookup(&gData.db , &dummy.node , &entryEq);

    if(!nodeFound) { //not found 
        return outNil(out);
    }

    //data found (give the value in response)
    const std::string &val = container_of(nodeFound , Entry , node)->val;
    assert(val.size() <= k_max_msg);
    return outStr(out , val.data() , val.size());

}

//SET function
static void doSet(std::vector<std::string> &cmd , Buffer &out) {

    Entry dummy;  // a dummy `Entry` just for the lookup
    dummy.key.swap(cmd[1]); //swap is the faster option to insert the data to string

    dummy.node.hcode = strHash((uint8_t *)dummy.key.data() , dummy.key.size()); //create the hash value

    //lookup the key in the database to check if its already exists
    HNode *nodeFound = hmLookup(&gData.db , &dummy.node , &entryEq);

    if(nodeFound){ //update the value if the key already exists
        container_of(nodeFound , Entry , node)->val.swap(cmd[2]);

    } else {
        //if not exists then create one 
        Entry *ent = new Entry();
        ent->key.swap(dummy.key);
        ent->val.swap(cmd[2]);
        ent->node.hcode = dummy.node.hcode;
        hmInsert(&gData.db , &ent->node);
    }
    
    return outNil(out);

}

static void doDel(std::vector<std::string> &cmd , Buffer &out) {

    //create a dummy Entry for lookup 
    Entry dummy;
    dummy.key.swap(cmd[1]);

    dummy.node.hcode = strHash((uint8_t *)dummy.key.data() , dummy.key.size());

    HNode *nodeFound = hmDelete(&gData.db , &dummy.node , &entryEq); //detach the node

    if(nodeFound) { //if node found delete delete it
        delete container_of(nodeFound , Entry , node);
    }

    return outInt(out  , nodeFound ? 1 : 0); // the number of deleted keys
}

static bool cbKeys(HNode *node , void *arg) {

    Buffer &out = *(Buffer *)arg;
    const std::string &key = container_of(node , Entry , node)->key;
    outStr(out , key.data() , key.size());
    return true;
}

static void doKeys(std::vector<std::string> & , Buffer &out) {
    outArr(out , (uint32_t)hmSize(&gData.db));
    hmForeach(&gData.db , &cbKeys , (void *)&out);
}


static void doRequest(std::vector<std::string> &cmd , Buffer &out) {

    //Handle the GET Request
    if(cmd.size() == 2 && cmd[0] == "get") {
        doGet(cmd , out);
        return;
    }

    //SET REquest
    if(cmd.size() == 3 && cmd[0] == "set") {
        doSet(cmd , out);
        return;
    }

    //delete request
    if(cmd.size() == 2 && cmd[0] == "del") {
        doDel(cmd , out);
        return;
    }

    if(cmd.size() == 1 && cmd[0] == "keys") {
        doKeys(cmd , out);
        return;
    }

    return outErr(out , ERR_UNKNOWN , "Unknown command!");

}

//function to reserve the spaces for the data in out buffer in the response
static void responseBegin(Buffer &out , size_t *header) {
    *header = out.size(); //message header postion
    bufAppendU32(out , 0); //reserve space

}

static size_t responseSize(Buffer &out , size_t header) {
    return out.size() - header - 4; //it returns exact length of the message 
}

static void responseEnd(Buffer &out , size_t header) {
    size_t msgSize = responseSize(out , header);
    if(msgSize > k_max_msg) {
        out.resize(header+4);
        outErr(out , ERR_TOO_BIG , "Response is too big.");
        msgSize = responseSize(out , header); //get the error message size
    }

    uint32_t len = (uint32_t)msgSize;
    memcpy(&out[header] , &len , 4);
}

static bool tryOneRequest(Conn *conn) {
    //parse the protocol message header
    if(conn->incoming.size() < 4) { //message size not recived so return false that there is more data ro read
        return false;
    }

    uint32_t len = 0;
    memcpy(&len , conn->incoming.data() , 4);

    if(len > k_max_msg) {
        msg("Too long message");
        conn->wantClose = true;
        return false; //want to close
    }

    //check for the recived message
    if(conn->incoming.size() < len + 4) { // the data is incomplete there to more data to be recieved 
        return false;
    }

    const uint8_t *request = &conn->incoming[4];

    std::vector<std::string> cmd;
    if(parseRequest(request , len , cmd) < 0) {
        conn->wantClose = true;
        return false;
    }

    size_t headerPos = 0;

    responseBegin(conn->outgoing , &headerPos);
    doRequest(cmd , conn->outgoing);
    responseEnd(conn->outgoing , headerPos);

    

     // application logic done! remove the request message.
     bufConsume(conn->incoming , (size_t)(4+len));

     return true;
    
} 

//set the file descriptors in non blocking mode
static void fdSetNonBlock(int fd) {
    errno = 0;
    int flags = fcntl(fd , F_GETFL , 0);

    if(errno) {
        die("Fcntl Error");
        return;
    }

    flags = flags | O_NONBLOCK; //add the nonblock option using the bit masking

    errno = 0;
    (void)fcntl(fd , F_SETFL , flags);
        if(errno) {
        die("Fcntl Error");
    }
}

static Conn * handleAccept(int fd) {

    //accpt the incomming request
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(fd , (struct sockaddr*)&client_addr , &addrlen);
    if(connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    }

    //print the clier ip address
    uint32_t ip = client_addr.sin_addr.s_addr; //this is stored in the little endian form
    std::cerr << "New Client IP : " 
          << (ip & 255) << "." 
          << ((ip >> 8) & 255) << "." 
          << ((ip >> 16) & 255) << "." 
          << (ip >> 24) << ":" 
          << ntohs(client_addr.sin_port) << std::endl;

    //set the new connection to be non blocking
    fdSetNonBlock(connfd);

    Conn *conn = new Conn();

    conn->fd = connfd;
    conn->wantRead = true; //at first the kernel should seek the data from the client 
    return conn;
    
}

static void handleWrite(Conn *conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd , conn->outgoing.data() , (size_t)conn->outgoing.size());

    if(rv < 0 && errno == EAGAIN) {
        return; //NOT AN Error
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->wantClose = true;    // error handling
    }  
    
    //consume the buffer after read
    bufConsume(conn->outgoing , (size_t)rv);

    if(conn->outgoing.size() == 0) { //all data is consumed
        conn->wantRead = true;
        conn->wantWrite = false;
        return;
    }
}

static void handleRead(Conn *conn) {

    uint8_t buf[64*1024]; //Create a 64KB slot on stack to store the recived data temporarily
    ssize_t rv = read(conn->fd , buf , (size_t)sizeof(buf));

    //if the read syscall returned an error
    if(rv < 0 && errno == EAGAIN) {
        return; //Resource Temporarily Unavailable (Try Again).
    }

    if(rv < 0) {
        msg_errno("read() Error");
        conn->wantClose = true;
        return;
    }
    if(rv == 0) {
        if(conn->incoming.size() == 0) {
            msg("Client Closed");
        } else {
            msg("Unexpected EOF");
        }

        conn->wantClose = true;
        return;
    }

    //Store the recieved data in a persistent storage (conn->incoming) 
    bufAppend(conn->incoming , buf , (size_t)rv);

   
    // TCP Stream Parser: A fast client might bundle multiple requests into a single read().
    // This loop aggressively extracts and handles every complete message frame back-to-back 
    // until the buffer is empty or holds an incomplete packet, preventing pipeline deadlocks.
    while(tryOneRequest(conn)) {}

    //update readiness information
    if(conn->outgoing.size() > 0) { //has a respose with it
        conn->wantRead = false;
        conn->wantWrite = true;
        
        //if the app has its response ready then directly send it to the client without waiting for the next round to come
        return handleWrite(conn);
    } //else : wantread = true;


}

int main() {

            //socket(domain , conn-type , protocol)
    int fd = socket(AF_INET , SOCK_STREAM , 0);
     if (fd < 0) {
        die("socket()");
    }
    
    /*
        1.AF_INET is for IPv4. Use AF_INET6 for IPv6 or dual-stack sockets.
        2.SOCK_STREAM is for TCP. Use SOCK_DGRAM for UDP.
        3.The 3rd argument is 0 and useless for our purposes.
     */
    int val = 1;
    //int setsockopt(int sockfd, int level, int optname,const void optval[.optlen], socklen_t optlen);
    setsockopt(fd ,SOL_SOCKET, SO_REUSEADDR , &val, sizeof(val));

    //bind
    struct sockaddr_in addr = {}; //initiazlise a sockadder_in sturcture
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234); //htons converts the little endian representation to big endian 
    addr.sin_addr.s_addr = htonl(0); // wildcard IP 0.0.0.0
    
    int rv = bind(fd , (const struct sockaddr *)&addr , sizeof(addr));

    if(rv) {
        die("bind()");
    }

     //set the listening socket (fd) as non block mode 
     fdSetNonBlock(fd);

    //listen
    rv = listen(fd , SOMAXCONN);
    if(rv) {
        die("listen()");
    }

    std::cout << "Server is listening on port 1234..." << std::endl;

    //start the event loop

    //1.Store all the connection fds in the conn container using an vector with fd as the index number
    /*Linux allocates the smallest available integer vairable to teh fd so it can be used as the array index*/
    std::vector<Conn *> fd2conn;

    std::vector<struct pollfd> pollArgs; 
    /*struct pollfd {
        int fd;	-> reference to the file descriptor 		
        short int events; -> POLLIN , POLLOUT , POLLERR	
        short int revents; -> filled by the kernel
    }*/

    while(true) {
        pollArgs.clear(); //first clear the old connection in case any connection is destroyed or closed that should also be removed

        //insert the listening socket to the zero index 
        struct pollfd pfd = {fd , POLLIN , 0}; //(basically it tells the poll function to wake it when a new connection request comes)
        pollArgs.push_back(pfd);

        //insert all the client connection to the poll
        for(Conn *conn : fd2conn) {

            if(!conn) {
                continue; 
            }

            struct pollfd pfd = {conn->fd , POLLERR , 0}; //POLLERR ->  Monitor the client socket for connection errors (broken pipes, crashes) by default 
            if(conn->wantRead) {
                pfd.events = pfd.events | POLLIN;
            }
            if(conn->wantWrite) {
                pfd.events |= POLLOUT;
            }
            pollArgs.push_back(pfd);
        }

        //now wait for the readiness of the sockets 
        int rv = poll(pollArgs.data() , (nfds_t)pollArgs.size() , -1); // Tell the kernel to watch our sockets;  block indefinitely until an event occurs (Your thread goes to sleep here.)
        if(rv < 0 && errno == EINTR) { // EINTR = Interrupted System Call
            continue;
        }
        if(rv < 0) {
            die("POLL()");
        }

        /**if we reached this line means one or more sockets have given the signal that they want to perform something these may be 
         * 1. The main listening socket placed in index 0 which indicate that new connection came 
         * 2. The Client sockets want to do some (read /write ) on our application
         */
        
         //1. Check if new connection request came
         if(pollArgs[0].revents) {

            //accept the new connection and generate a Conn object
            Conn *conn = handleAccept(fd);

            if(conn != NULL) {

                //put the connection opj to the map
                if(fd2conn.size() <= (size_t)conn->fd){
                    fd2conn.resize((size_t)conn->fd+1);
                }
                assert(!fd2conn[conn->fd]); //check that the slot is empty (means the slot is not allocated to any other active socket)
                fd2conn[conn->fd] = conn;

            }
         }

         //2. Now handle the event from the client sockets
         for(size_t i = 1 ; i < pollArgs.size() ; i++) {
            uint32_t ready = pollArgs[i].revents;
            if(ready == 0) {
                continue;
            }

            Conn *conn = fd2conn[pollArgs[i].fd];

            if(ready & POLLIN) {
                assert(conn->wantRead);
                handleRead(conn);
            }
            if(ready & POLLOUT) {
                assert(conn->wantWrite);
                handleWrite(conn);
            }

            // close the socket from socket error or application logic
            if((ready & POLLERR) || conn->wantClose) {
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
         }

    }
    
    return 0;

}
